# Run h2 in local and enable its console on http://localhost:8080/h2-console
spring:
  h2.console:
    enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    data: "classpath*:db/local/data-h2.sql"
    initialization-mode: always