name: Build and Test
on: [push]
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: -B -ntp
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile with Maven
        run: make build args="${MAVEN_ARGS}"
      - name: Test with Maven
        run: make test args="${MAVEN_ARGS}"
      - name: Code quality
        run: make quality args="-B -ntp -Dsonar.java.binaries=target/classes -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sanadhis -Dsonar.projectKey=sanadhis_data-api"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
